// Authoritative GSE company registry.
// domain is used for Clearbit logo API and Google S2 favicon fallback.
// Keep this file as the single source of truth for logos across the app.
export const GSE_COMPANIES = {
  AADS:     { name: 'AngloGold Ashanti Depository Shares', domain: 'anglogoldashanti.com' },
  ACCESS:   { name: 'Access Bank Ghana',                   domain: 'accessbankplc.com' },
  ADB:      { name: 'Agricultural Development Bank',       domain: 'agricbank.com' },
  AGA:      { name: 'AngloGold Ashanti',                   domain: 'anglogoldashanti.com' },
  ALLGH:    { name: 'Atlantic Lithium Limited',            domain: 'atlanticlithium.com.au' },
  ALW:      { name: 'Aluworks Ltd',                        domain: 'aluworks.com' },
  ASG:      { name: 'Asante Gold Corporation',             domain: 'asantegold.com' },
  BOPP:     { name: 'Benso Oil Palm Plantation',           domain: 'boppplc.com' },
  CAL:      { name: 'CalBank Plc',                         domain: 'calbank.net' },
  CLYD:     { name: 'Clydesstone (Ghana) Ltd',             domain: 'clydestone.com' },
  CMLT:     { name: 'Camelot Ghana Ltd',                   domain: 'camelotprint.com' },
  CPC:      { name: 'Cocoa Processing Company',            domain: 'cpc.com.gh' },
  DASPHARMA:{ name: 'Dannex Ayrton Starwin Plc',           domain: 'dasplcgh.com' },
  EGH:      { name: 'Ecobank Ghana',                       domain: 'ecobank.com' },
  EGL:      { name: 'Enterprise Group',                    domain: 'enterprisegroup.net.gh' },
  ETI:      { name: 'Ecobank Transnational',               domain: 'ecobank.com' },
  FAB:      { name: 'First Atlantic Bank',                 domain: 'firstatlanticbank.com.gh', logoUrl: 'https://firstatlanticbank.com.gh/logo.webp' },
  FML:      { name: 'Fan Milk Plc',                        domain: 'danone.com' },
  GCB:      { name: 'GCB Bank',                            domain: 'gcbbank.com.gh' },
  GGBL:     { name: 'Guinness Ghana Breweries',            domain: 'guinnessghanaplc.com' },
  GLD:      { name: 'NewGold Issuer Limited',              domain: null },
  GOIL:     { name: 'GOIL Plc',                            domain: 'goil.com.gh' },
  HFC:      { name: 'Republic Bank Ghana',                 domain: 'republicghana.com' },
  HORDS:    { name: 'Hords Ltd',                           domain: 'hordslimitedgh.com' },
  IIL:      { name: 'Intravenous Infusions Ltd',           domain: 'iil.com.gh', logoUrl: 'https://iil.com.gh/wp-content/uploads/2022/03/cropped-IIL-Logo-298x152.png' },
  KAS:      { name: 'Kasapreko PLC',                       domain: 'kasapreko.com' },
  MAC:      { name: 'Mega African Capital Ltd',            domain: null },
  MLC:      { name: 'Mechanical Lloyd Company',            domain: 'mechlloyd.com' },
  MMH:      { name: 'Meridian-Marshalls Holdings',         domain: null },
  MTNGH:    { name: 'MTN Ghana',                           domain: 'mtn.com' },
  PBC:      { name: 'Produce Buying Company Ltd',          domain: 'pbcgh.com', logoUrl: 'https://www.pbcgh.com/images/pbclogo.png' },
  POP:      { name: 'Pesewa One PLC',                      domain: null },
  PZC:      { name: 'PZ Cussons Ghana',                    domain: 'pzcussons.com.gh' },
  RBGH:     { name: 'Republic Bank Ghana',                 domain: 'republicghana.com' },
  SAMBA:    { name: 'Samba Foods Ltd',                     domain: 'sambafoodsghana.org' },
  SCB:      { name: 'Standard Chartered Ghana',            domain: 'sc.com' },
  SCBPREF:  { name: 'Standard Chartered Ghana Pref',      domain: 'sc.com' },
  SIC:      { name: 'SIC Insurance',                       domain: 'sic-gh.com' },
  SOGEGH:   { name: 'Societe Generale Ghana',              domain: 'societegenerale.com' },
  TBL:      { name: 'Trust Bank Ltd (The Gambia)',         domain: 'trustbankgambia.com' },
  TLW:      { name: 'Tullow Oil PLC',                      domain: 'tullowoil.com' },
  TOTAL:    { name: 'TotalEnergies Marketing Ghana',       domain: 'totalenergies.com.gh' },
  UNIL:     { name: 'Unilever Ghana',                      domain: 'unileverghana.com' },
  ZEN:      { name: 'Zen Petroleum',                       domain: 'zenpetroleum.com' },
}

export function getCompany(symbol) {
  return GSE_COMPANIES[symbol] ?? { name: symbol, domain: null }
}
